name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'dev'
jobs:
  issue_parser:
    runs-on: ubuntu-latest
    name: Terraform destroy
    steps:      
    - name: Terraform destroy on github action aws v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      uses: md1810/terraform-destroy-on-action@v5.2
      with:
        org_name: "jcelestino-15"
        repo_name: "team-rocket-app"
